# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('ledger', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsProduct',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('min_contribution', models.DecimalField(decimal_places=2, default=100, max_digits=19)),
                ('max_contribution', models.DecimalField(decimal_places=2, default=100000, max_digits=19)),
                ('allowed_frequencies', models.JSONField(default=list)),
                ('payout_policy', models.CharField(default='END_OF_TERM', max_length=20)),
                ('allow_early_payout', models.BooleanField(default=False)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SavingsPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('product_config', models.JSONField(default=dict)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('BIYEARLY', 'Bi-yearly'), ('YEARLY', 'Yearly')], max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PAUSED', 'Paused')], default='DRAFT', max_length=10)),
                ('payout_policy', models.CharField(default='END_OF_TERM', max_length=20)),
                ('total_contributed', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_plans', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='savings.savingsproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('VALIDATED', 'Validated'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='savings_payouts', to='ledger.ledgertransaction')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='savings.savingsplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('PAID', 'Paid'), ('MISSED', 'Missed'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=32)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='savings.savingsplan')),
            ],
            options={
                'ordering': ['plan', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='SavingsContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_contributions', to='ledger.ledgertransaction')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='savings_contribution', to='payments.payment')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='savings.savingsplan')),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='savings.savingsscheduleitem')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('contribution_frequency', models.CharField(default='MONTHLY', max_length=12)),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='savings_goals', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('target_amount__gt', 0)), name='goal_positive_target')],
            },
        ),
        migrations.AddIndex(
            model_name='savingsplan',
            index=models.Index(fields=['customer', '-created_at'], name='savings_sav_custome_592dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='savingsplan',
            index=models.Index(fields=['status'], name='savings_sav_status_412721_idx'),
        ),
        migrations.AddConstraint(
            model_name='savingsplan',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='savings_plan_positive_amount'),
        ),
        migrations.AddIndex(
            model_name='savingsscheduleitem',
            index=models.Index(fields=['status', 'due_date'], name='savings_sav_status_42a015_idx'),
        ),
        migrations.AddConstraint(
            model_name='savingsscheduleitem',
            constraint=models.UniqueConstraint(fields=('plan', 'sequence'), name='uniq_schedule_seq'),
        ),
        migrations.AddConstraint(
            model_name='savingsscheduleitem',
            constraint=models.UniqueConstraint(fields=('plan', 'due_date'), name='uniq_schedule_date'),
        ),
    ]
