# Generated by Django 5.1.4 on 2026-09-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsscheduleitem',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
