# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTerritory',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=60)),
                ('lga', models.CharField(blank=True, default='', max_length=80)),
                ('communities', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('txn_type', models.CharField(choices=[('CASH_COLLECTION', 'Cash collection'), ('CUSTOMER_PAYOUT', 'Customer payout')], db_index=True, max_length=18)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('VALIDATED', 'Validated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='INITIATED', max_length=10)),
                ('client_reference', models.CharField(blank=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('purpose', models.CharField(default='SAVINGS_CONTRIBUTION', max_length=24)),
                ('target', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=250)),
                ('performed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('txn_type', models.CharField(blank=True, default='', max_length=18)),
                ('basis', models.CharField(choices=[('PERCENT', 'Percent of transaction amount'), ('FIXED', 'Fixed amount per transaction')], default='PERCENT', max_length=8)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('max_amount', models.DecimalField(decimal_places=2, default=1000000, max_digits=19)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued'), ('PAID', 'Paid')], default='ACCRUED', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=12)),
                ('business_name', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('onboarded_at', models.DateTimeField(auto_now_add=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervised_agents', to='agents.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agent_code'],
            },
        ),
        migrations.CreateModel(
            name='AgentDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(db_index=True, max_length=120, unique=True)),
                ('device_name', models.CharField(blank=True, default='', max_length=120)),
                ('os_version', models.CharField(blank=True, default='', max_length=40)),
                ('app_version', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISABLED', 'Disabled')], default='ACTIVE', max_length=10)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='agents.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentFloatMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('IN', 'In (collections increase agent-held cash)'), ('OUT', 'Out (payouts/settlements reduce it)')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='float_movements', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('single_transaction_limit', models.DecimalField(decimal_places=2, default=50000, max_digits=19)),
                ('daily_cash_in_limit', models.DecimalField(decimal_places=2, default=200000, max_digits=19)),
                ('daily_payout_limit', models.DecimalField(decimal_places=2, default=100000, max_digits=19)),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=2000000, max_digits=19)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='limits', to='agents.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('PENDING_SETTLEMENT', 'Pending settlement'), ('SETTLEMENT_REQUESTED', 'Settlement requested'), ('UNDER_REVIEW', 'Under review'), ('APPROVED', 'Approved'), ('SETTLED', 'Settled'), ('REJECTED', 'Rejected')], default='PENDING_SETTLEMENT', max_length=22)),
                ('reason', models.TextField(blank=True, default='')),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='agents.agent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
