# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('customers', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettlement',
            name='ledger_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_settlements', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='agentsettlement',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentsettlement',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentsettlement',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentfloatmovement',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='float_movements', to='agents.agentsettlement'),
        ),
        migrations.AddField(
            model_name='agent',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='agents.agentterritory'),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_transactions', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.agentdevice'),
        ),
        migrations.AddField(
            model_name='agenttransaction',
            name='ledger_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_transactions', to='ledger.ledgertransaction'),
        ),
        migrations.AddField(
            model_name='agentfloatmovement',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='float_movement', to='agents.agenttransaction'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agents.commissionrule'),
        ),
        migrations.AddField(
            model_name='commissiontransaction',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='agents.agenttransaction'),
        ),
        migrations.AddIndex(
            model_name='agenttransaction',
            index=models.Index(fields=['agent', '-performed_at'], name='agents_agen_agent_i_0ec5b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='agenttransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='agent_txn_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='agenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_agent_txn_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='commissiontransaction',
            constraint=models.UniqueConstraint(fields=('source', 'rule'), name='uniq_commission_per_rule'),
        ),
    ]
