# Generated by Django 5.1.4 on 2026-09-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=8)),
                ('date_key', models.CharField(max_length=8)),
                ('last_number', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_reference_sequence',
                'unique_together': {('prefix', 'date_key')},
            },
        ),
    ]
