# Generated by Django 5.1.4 on 2026-09-21 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(default='FOOD', max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.CharField(max_length=40)),
                ('performed_on', models.DateField()),
                ('notes', models.TextField(blank=True, default='')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
            options={
                'ordering': ['performed_on'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('harvested_on', models.DateField()),
                ('buyer_name', models.CharField(blank=True, default='', max_length=120)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_type', models.CharField(choices=[('SEED', 'Seed'), ('FERTILIZER', 'Fertilizer'), ('AGROCHEMICAL', 'Agrochemical'), ('LABOUR', 'Labour'), ('TRANSPORT', 'Transport'), ('STORAGE', 'Storage'), ('IRRIGATION', 'Irrigation'), ('OTHER', 'Other')], max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit', models.CharField(default='unit', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InputSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('lga', models.CharField(blank=True, default='', max_length=80)),
                ('input_types', models.JSONField(default=list)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
