# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriculture', '0001_initial'),
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmactivity',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='farmers.farmseason'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='season',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='harvest', to='farmers.farmseason'),
        ),
        migrations.AddField(
            model_name='inputrequirement',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='input_requirements', to='farmers.farmseason'),
        ),
        migrations.AddField(
            model_name='inputrequirement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agriculture.inputsupplier'),
        ),
    ]
