# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_day', models.CharField(blank=True, default='', max_length=20)),
                ('meeting_place', models.CharField(blank=True, default='', max_length=160)),
                ('member_count', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cooperative', to='organizations.organization')),
                ('president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CooperativeMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('SECRETARY', 'Secretary'), ('TREASURER', 'Treasurer'), ('PRESIDENT', 'President')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('cooperative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='cooperatives.cooperative')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cooperative_memberships', to='customers.customer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cooperative', 'customer'), name='uniq_coop_member')],
            },
        ),
    ]
