# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('signal', models.CharField(max_length=40)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('parameters', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('decision', models.CharField(max_length=10)),
                ('model_version', models.CharField(default='rules-v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assessment', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rule_code', models.CharField(max_length=40)),
                ('input_value', models.CharField(max_length=250)),
                ('score', models.PositiveIntegerField()),
                ('weight', models.CharField(max_length=10)),
                ('explanation', models.CharField(max_length=250)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factors', to='risk.riskassessment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
