# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_label', models.CharField(blank=True, default='', max_length=120)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login failed'), ('LOGOUT', 'Logout'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('REVERSE', 'Reverse'), ('REFUND', 'Refund'), ('DISBURSE', 'Disburse'), ('SETTLE', 'Settle'), ('SUSPEND', 'Suspend'), ('REINSTATE', 'Reinstate'), ('VERIFY', 'Verify'), ('FLAG', 'Flag'), ('CLEAR', 'Clear'), ('EXPORT', 'Export'), ('CONFIG_CHANGE', 'Configuration change'), ('REVIEW', 'Review'), ('ASSIGN', 'Assign')], db_index=True, max_length=20)),
                ('resource_type', models.CharField(db_index=True, max_length=60)),
                ('resource_id', models.CharField(db_index=True, max_length=64)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('request_id', models.CharField(blank=True, default='', max_length=40)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2ab5ff_idx'), models.Index(fields=['actor', '-occurred_at'], name='audit_audit_actor_i_322ce5_idx')],
            },
        ),
    ]
