"""Role & permission bootstrap (spec §11).

15 roles, 40+ granular permissions. Seeded via data migration + management
command; NEVER granted through is_staff shortcuts.
"""

ROLE_PERMISSIONS: dict[str, list[str]] = {
    "CUSTOMER": [
        "customer.read.self",
        "customer.update.self",
        "savings.read.self",
        "savings.write.self",
        "goals.read.self",
        "goals.write.self",
        "loan.read.self",
        "loan.apply.self",
        "payment.read.self",
        "payment.initialize.self",
        "transaction.read.self",
        "notification.read.self",
        "support.read.self",
        "support.write.self",
    ],
    "AGENT": [
        "customer.read.self",  # scoped to served customers via object checks
        "customer.create.assisted",
        "agent.read.self",
        "agent.collect.self",
        "agent.payout.self",
        "agent.settlement.request.self",
        "transaction.read.self",
        "support.write.self",
    ],
    "AGENT_SUPERVISOR": [
        "agent.read",
        "agent.manage",
        "agent.settlement.review",
        "report.view.agent",
    ],
    "FIELD_OFFICER": [
        "customer.read",
        "kyc.read",
        "verification.perform",
        "report.view.customer",
    ],
    "LOAN_OFFICER": [
        "customer.read",
        "loan.read",
        "loan.review",
        "loan.approve",
        "loan.disburse",
        "risk.read",
        "report.view.loan",
    ],
    "KYC_OFFICER": [
        "customer.read",
        "kyc.read",
        "kyc.review",
        "document.read",
        "report.view.kyc",
    ],
    "RISK_OFFICER": [
        "risk.read",
        "risk.manage",
        "fraud.read",
        "loan.read",
        "report.view.risk",
    ],
    "FINANCE_OFFICER": [
        "ledger.view",
        "ledger.post",
        "ledger.reverse",
        "payment.view",
        "settlement.approve",
        "reconciliation.view",
        "reconciliation.resolve",
        "report.view.finance",
        "export.finance",
    ],
    "SUPPORT_AGENT": [
        "customer.read",
        "support.read",
        "support.write",
        "payment.read.limited",
        "transaction.read.limited",
    ],
    "COOPERATIVE_ADMIN": [
        "cooperative.read.self",
        "cooperative.manage.self",
        "customer.read.self",
        "report.view.cooperative",
    ],
    "REGIONAL_MANAGER": [
        "customer.read",
        "agent.read",
        "cooperative.read",
        "report.view.region",
        "loan.read",
    ],
    "ADMIN": [
        "customer.read", "customer.update", "customer.manage",
        "agent.read", "agent.manage",
        "cooperative.read", "cooperative.manage",
        "savings.read", "savings.manage",
        "loan.read", "loan.review",
        "payment.view", "payment.manage",
        "ledger.view", "ledger.post",
        "kyc.read", "kyc.review",
        "risk.read", "risk.manage",
        "fraud.read", "fraud.manage",
        "support.read", "support.write", "support.manage",
        "report.view", "export.general",
        "audit.view",
        "verification.perform",
        "settlement.approve",
        "reconciliation.view", "reconciliation.resolve",
        "document.read",
    ],
    "SUPER_ADMIN": ["*"],
}

ROLE_DESCRIPTIONS = {
    "CUSTOMER": "RFUND saver / borrower",
    "AGENT": "Local cash collection and payout agent",
    "AGENT_SUPERVISOR": "Oversees agents in a region",
    "FIELD_OFFICER": "Field verification of customers and farms",
    "LOAN_OFFICER": "Reviews and approves loan applications",
    "KYC_OFFICER": "Reviews identity verification",
    "RISK_OFFICER": "Manages risk rules and assessments",
    "FINANCE_OFFICER": "Ledger operations, settlement approval, reconciliation",
    "SUPPORT_AGENT": "Customer support",
    "COOPERATIVE_ADMIN": "Manages a cooperative",
    "REGIONAL_MANAGER": "Regional oversight",
    "ADMIN": "Platform administration",
    "SUPER_ADMIN": "Unrestricted platform administration",
}
