# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('ledger', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('term_values', models.JSONField(default=list)),
                ('repayment_frequency', models.CharField(default='MONTHLY', max_length=12)),
                ('interest_method', models.CharField(default='FLAT', max_length=24)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fees', models.JSONField(default=dict)),
                ('penalty_policy', models.JSONField(default=dict)),
                ('allocation_order', models.JSONField(default=list)),
                ('eligibility_rules', models.JSONField(default=dict)),
                ('required_documents', models.JSONField(default=list)),
                ('status', models.CharField(default='ACTIVE', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('product_config', models.JSONField(default=dict)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=19)),
                ('term_months', models.PositiveIntegerField()),
                ('purpose', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('VERIFICATION_REQUIRED', 'Verification required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OFFERED', 'Offered'), ('ACCEPTED', 'Accepted'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=22)),
                ('business_info', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('term_months', models.PositiveIntegerField()),
                ('total_repayable', models.DecimalField(decimal_places=2, max_digits=19)),
                ('first_payment_date', models.DateField()),
                ('expires_on', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='loans.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('product_config', models.JSONField(default=dict)),
                ('principal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('interest_method', models.CharField(default='FLAT', max_length=24)),
                ('term_months', models.PositiveIntegerField()),
                ('total_interest', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, max_digits=19)),
                ('outstanding_interest', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('outstanding_fees', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELINQUENT', 'Delinquent'), ('DEFAULTED', 'Defaulted'), ('RESTRUCTURED', 'Restructured'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=14)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='customers.customer')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='ledger.ledgertransaction')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='loans.loanapplication')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='loans.loanproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('allocation', models.JSONField(default=dict)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayments', to='ledger.ledgertransaction')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='loans.loan')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_repayment', to='payments.payment')),
            ],
            options={
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('due_date', models.DateField(db_index=True)),
                ('principal_due', models.DecimalField(decimal_places=2, max_digits=19)),
                ('interest_due', models.DecimalField(decimal_places=2, max_digits=19)),
                ('fees_due', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('penalty_due', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('DUE', 'Due'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('LATE', 'Late'), ('WAIVED', 'Waived'), ('RESTRUCTURED', 'Restructured')], default='UPCOMING', max_length=16)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayment_schedule', to='loans.loan')),
            ],
            options={
                'ordering': ['loan', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('reason', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('OUTSTANDING', 'Outstanding'), ('WAIVED', 'Waived'), ('PAID', 'Paid')], default='OUTSTANDING', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penalties', to='loans.loan')),
                ('waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='loans.repaymentscheduleitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['customer', '-created_at'], name='loans_loana_custome_f90738_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['state'], name='loans_loana_state_3a20cd_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['customer', '-created_at'], name='loans_loan_custome_62f627_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='loans_loan_status_962e99_idx'),
        ),
        migrations.AddConstraint(
            model_name='repaymentscheduleitem',
            constraint=models.UniqueConstraint(fields=('loan', 'sequence'), name='uniq_repayment_seq'),
        ),
    ]
