# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agriculture', '0001_initial'),
        ('cooperatives', '0001_initial'),
        ('customers', '0001_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('primary_crops', models.JSONField(default=list)),
                ('farming_type', models.CharField(default='SMALLHOLDER', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='farmers', to='cooperatives.cooperative')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_profile', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('state', models.CharField(max_length=60)),
                ('lga', models.CharField(blank=True, default='', max_length=80)),
                ('community', models.CharField(blank=True, default='', max_length=120)),
                ('size_hectares', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('ownership', models.CharField(default='OWNED', max_length=20)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='farmers.farmerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmSeason',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season_name', models.CharField(max_length=40)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('expected_yield_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('HARVESTED', 'Harvested'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='agriculture.crop')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='farmers.farm')),
            ],
            options={
                'ordering': ['-starts_on'],
            },
        ),
        migrations.CreateModel(
            name='FieldVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('photos', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='REQUESTED', max_length=12)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_verifications', to='loans.loanapplication')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='farmers.farm')),
                ('verifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
