# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_reference', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('internal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('MISSING_PROVIDER', 'Missing on provider'), ('MISSING_INTERNAL', 'Missing internally'), ('AMOUNT_MISMATCH', 'Amount mismatch'), ('DUPLICATE', 'Duplicate'), ('PENDING', 'Pending'), ('MANUAL_REVIEW', 'Manual review')], default='PENDING', max_length=18)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=10)),
                ('matched_count', models.PositiveIntegerField(default=0)),
                ('exception_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('resolution', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exception', to='settlements.reconciliationitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='reconciliationitem',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='settlements.reconciliationrun'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationitem',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('run', 'provider_reference'), name='uniq_recon_item_provider_ref'),
        ),
    ]
