# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('ledger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=32, unique=True)),
                ('purpose', models.CharField(choices=[('SAVINGS_CONTRIBUTION', 'Savings contribution'), ('GOAL_FUNDING', 'Savings goal funding'), ('LOAN_REPAYMENT', 'Loan repayment'), ('ACCOUNT_FUNDING', 'Account funding')], db_index=True, max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('INITIALIZED', 'Initialized'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('SETTLED', 'Settled')], default='INITIALIZED', max_length=12)),
                ('method', models.CharField(blank=True, choices=[('CARD', 'Card'), ('BANK_TRANSFER', 'Bank transfer'), ('USSD', 'USSD'), ('AGENT_CASH', 'Agent cash'), ('WALLET', 'Wallet')], default='', max_length=16)),
                ('provider', models.CharField(blank=True, default='', max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('target', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=250)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, default='', max_length=120)),
                ('client_reference', models.CharField(blank=True, default='', max_length=120)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='customers.customer')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ledger.ledgertransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(max_length=12)),
                ('authorization_url', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=60)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payments.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('provider_reference', models.CharField(db_index=True, max_length=120)),
                ('event_type', models.CharField(blank=True, default='', max_length=60)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(max_length=20)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('reconciled', models.BooleanField(db_index=True, default=False)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider', 'provider_reference'), name='uniq_provider_event_reference')],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('event_id', models.CharField(db_index=True, max_length=120)),
                ('event_type', models.CharField(blank=True, default='', max_length=60)),
                ('payload', models.JSONField()),
                ('signature_valid', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processing_status', models.CharField(default='RECEIVED', max_length=16)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='payments.payment')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(db_index=True, max_length=20)),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('account_number', models.CharField(blank=True, default='', max_length=40)),
                ('bank_name', models.CharField(blank=True, default='', max_length=80)),
                ('bank_code', models.CharField(blank=True, default='', max_length=20)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FROZEN', 'Frozen'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=8)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='virtual_accounts', to='customers.customer')),
            ],
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-created_at'], name='payments_pa_custome_a935a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', '-created_at'], name='payments_pa_status_21ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['provider', 'provider_reference'], name='payments_pa_provide_44281d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_payment_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_webhook_event'),
        ),
        migrations.AddConstraint(
            model_name='virtualaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('account_number', ''), _negated=True), fields=('provider', 'account_number'), name='uniq_virtual_account_number'),
        ),
    ]
