# Generated by Django 5.1.4 on 2026-09-21 18:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('type', models.CharField(choices=[('COOPERATIVE', 'Cooperative'), ('NGO', 'NGO'), ('PARTNER', 'Partner'), ('FUNDER', 'Institutional funder')], db_index=True, max_length=14)),
                ('registration_number', models.CharField(blank=True, default='', max_length=60)),
                ('state', models.CharField(blank=True, default='', max_length=60)),
                ('lga', models.CharField(blank=True, default='', max_length=80)),
                ('community', models.CharField(blank=True, default='', max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=12)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
