# Generated by Django 5.1.4 on 2026-09-21 18:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('NIN', 'National Identity Number'), ('BVN', 'Bank Verification Number'), ('PASSPORT', 'International passport'), ('DRIVERS_LICENSE', "Driver's licence"), ('VOTERS_CARD', "Voter's card"), ('OTHER', 'Other')], max_length=20)),
                ('number_encrypted', models.TextField()),
                ('storage_key', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(default='NG', max_length=2)),
                ('issued_at', models.DateField(blank=True, null=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_documents', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='NOT_STARTED', max_length=14)),
                ('level', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('ENHANCED', 'Enhanced')], default='BASIC', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_profile', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='KYCReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('before_status', models.CharField(max_length=14)),
                ('after_status', models.CharField(max_length=14)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='identity.kycprofile')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=40)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_verifications', to='customers.customer')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='identity.identitydocument')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='identitydocument',
            constraint=models.UniqueConstraint(fields=('customer', 'doc_type'), name='uniq_customer_doc_type'),
        ),
        migrations.AddIndex(
            model_name='kycprofile',
            index=models.Index(fields=['status'], name='identity_ky_status_45256e_idx'),
        ),
        migrations.AddConstraint(
            model_name='kycverification',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider', 'provider_reference'), name='uniq_kyc_provider_reference'),
        ),
    ]
